[Checkpoint] - Refactor attempt to use structs and an Enum
This is not working because

    > error[E0599]: no method named `get_roots` found for enum `DType` in the current scope